commit_messages_list = [
    'ci(auth): update API documentation',
    'perf(readme): add password reset functionality',
    'fix(backend): update deployment script',
    'style(deps): fix broken link in footer',
    'refactor(utils): optimize image loading',
    'build(api): resolve issue with data fetching',
    'style(db): enhance error handling',
    'ci(deps): remove unused imports',
    'refactor(config): refactor date handling logic',
    'chore(config): improve query performance',
    'docs(frontend): upgrade dependencies',
    'fix(api): improve query performance',
    'test(api): add user login feature',
    'style(db): fix broken link in footer',
    'build(deps): optimize image loading',
    'build(ui): remove deprecated functions',
    'refactor(utils): upgrade dependencies',
    'perf(config): update API documentation',
    'refactor(ui): update README with new commands',
    'fix(utils): add new dashboard widget',
    'ci(frontend): resolve issue with data fetching',
    'fix(auth): add password reset functionality',
    'test(api): fix typo in config file',
    'style(backend): add new dashboard widget',
    'test(db): resolve issue with data fetching',
    'feat(config): remove unused imports',
    'style(config): simplify authentication flow',
    'style(db): remove deprecated functions',
    'fix(deps): add missing unit tests',
    'fix(auth): update deployment script',
    'refactor(api): improve query performance',
    'feat(backend): add new dashboard widget',
    'ci(api): remove deprecated functions',
    'fix(readme): improve query performance',
    'chore(auth): refactor date handling logic',
    'ci(db): add password reset functionality',
    'chore(frontend): fix typo in config file',
    'feat(readme): update README with new commands',
    'perf(ui): update deployment script',
    'style(frontend): enhance error handling',
    'build(config): update README with new commands',
    'refactor(readme): improve query performance',
    'fix(deps): update deployment script',
    'build(config): upgrade dependencies',
    'ci(api): update deployment script',
    'ci(api): add password reset functionality',
    'refactor(ui): fix UI alignment issues',
    'docs(utils): improve query performance',
    'perf(ui): fix typo in config file',
    'refactor(ui): add user login feature',
    'docs(backend): update API documentation',
    'test(db): enhance error handling',
    'feat(api): resolve issue with data fetching',
    'ci(frontend): enhance error handling',
    'docs(deps): improve query performance',
    'docs(utils): fix UI alignment issues',
    'perf(api): update API documentation',
    'style(utils): resolve issue with data fetching',
    'refactor(frontend): update API documentation',
    'style(auth): add user login feature',
    'build(ui): upgrade dependencies',
    'ci(auth): fix UI alignment issues',
    'chore(deps): add missing unit tests',
    'ci(frontend): add new dashboard widget',
    'ci(config): fix UI alignment issues',
    'style(db): remove unused imports',
    'chore(db): upgrade dependencies',
    'docs(utils): fix broken link in footer',
    'build(config): enhance error handling',
    'build(utils): add new dashboard widget',
    'fix(backend): add missing unit tests',
    'docs(frontend): refactor date handling logic',
    'refactor(config): enhance error handling',
    'ci(config): add new dashboard widget',
    'ci(config): fix broken link in footer',
    'ci(frontend): update API documentation',
    'feat(frontend): add dark mode support',
    'fix(auth): add password reset functionality',
    'docs(deps): add dark mode support',
    'docs(auth): remove unused imports',
    'feat(readme): add new dashboard widget',
    'test(api): resolve issue with data fetching',
    'fix(api): add password reset functionality',
    'fix(db): remove unused imports',
    'ci(config): update API documentation',
    'style(readme): improve query performance',
    'perf(backend): remove unused imports',
    'test(readme): remove unused imports',
    'test(ui): remove deprecated functions',
    'test(db): optimize image loading',
    'perf(readme): remove unused imports',
    'chore(utils): fix broken link in footer',
    'perf(frontend): update README with new commands',
    'fix(db): enhance error handling',
    'style(backend): update README with new commands',
    'style(deps): remove deprecated functions',
    'fix(backend): fix UI alignment issues',
    'ci(config): enhance error handling',
    'chore(db): fix UI alignment issues',
    'ci(readme): fix broken link in footer',
     'style(api): add custom hooks for API calls',
    'docs(cache): introduce dark mode toggle',
    'style(middleware): add role-based access control',
    'ci(deps): update API response schema',
    'feat(cache): add pagination to user list',
    'build(middleware): add skeleton loader for UI',
    'ci(config): implement debounce for search',
    'perf(auth): fix typo in error message',
    'ci(notifications): fix token expiration bug',
    'refactor(cache): add integration tests for login',
    'test(deps): replace axios with fetch API',
    'test(deps): fix broken pagination',
    'style(backend): remove obsolete API endpoints',
    'docs(readme): add integration tests for login',
    'perf(backend): configure Sentry for error tracking',
    'test(api): fix loading spinner visibility',
    'refactor(middleware): add pagination to user list',
    'style(config): improve security headers',
    'fix(db): add Dockerfile for deployment',
    'chore(routing): update package-lock.json',
    'refactor(frontend): optimize image caching',
    'refactor(cache): configure Sentry for error tracking',
    'docs(deps): simplify form validation',
    'chore(config): update ESLint configuration',
    'feat(routing): remove unused CSS classes',
    'build(deps): adjust button padding',
    'feat(config): improve loading speed of dashboard',
    'refactor(readme): adjust button padding',
    'test(notifications): enable gzip compression',
    'docs(db): enhance user role validation',
    'chore(db): fix mobile navigation bug',
    'test(frontend): fix broken pagination',
    'chore(api): enable gzip compression',
    'docs(utils): improve loading speed of dashboard',
    'feat(api): update ESLint configuration',
    'chore(middleware): implement debounce for search',
    'perf(db): refactor user permissions logic',
    'feat(notifications): adjust button padding',
    'test(db): enhance user role validation',
    'test(utils): fix typo in error message',
    'ci(readme): add contributing guidelines',
    'fix(middleware): optimize image caching',
    'docs(api): enhance user role validation',
    'test(middleware): fix broken pagination',
    'chore(api): fix token expiration bug',
    'refactor(backend): implement debounce for search',
    'feat(readme): add custom error pages',
    'style(notifications): implement debounce for search',
    'perf(cache): reduce bundle size',
    'style(ui): adjust button padding',
    'fix(utils): enhance user role validation',
    'test(backend): refactor user permissions logic',
    'test(ui): fix typo in error message',
    'refactor(ui): simplify form validation',
    'ci(db): fix race condition in API calls',
    'ci(ui): implement debounce for search',
    'perf(config): update deployment workflow',
    'feat(notifications): refactor state management',
    'docs(config): enable gzip compression',
    'test(config): add skeleton loader for UI',
    'style(notifications): fix cache invalidation issue',
    'refactor(notifications): fix token expiration bug',
    'perf(readme): implement push notifications',
    'fix(notifications): replace axios with fetch API',
    'docs(backend): fix loading spinner visibility',
    'test(api): add contributing guidelines',
    'ci(notifications): remove redundant console logs',
    'style(cache): add responsive design support',
    'fix(cache): add responsive design support',
    'style(middleware): add pagination to user list',
    'test(api): enhance user role validation',
    'build(deps): fix token expiration bug',
    'ci(readme): add custom error pages',
    'ci(routing): implement push notifications',
    'docs(deps): remove hardcoded values',
    'test(backend): update deployment workflow',
    'chore(middleware): improve loading speed of dashboard',
    'style(readme): add contributing guidelines',
    'style(ui): improve loading speed of dashboard',
    'style(db): add role-based access control',
    'chore(ui): implement debounce for search',
    'perf(cache): refactor state management',
    'test(frontend): add pagination to user list',
    'build(auth): remove unused CSS classes',
    'style(utils): add role-based access control',
    'perf(config): simplify form validation',
    'perf(backend): fix layout issue in profile page',
    'test(notifications): fix layout issue in profile page',
    'perf(config): remove hardcoded values',
    'chore(config): reduce bundle size',
    'fix(config): add pagination to user list',
    'test(routing): optimize SQL queries',
    'style(notifications): replace axios with fetch API',
    'fix(deps): update Swagger docs',
    'test(frontend): remove unused CSS classes',
    'build(deps): add custom hooks for API calls',
    'style(routing): add custom hooks for API calls',
    'perf(utils): optimize SQL queries',
    'docs(ui): improve security headers',
    'style(cache): add skeleton loader for UI',
    'fix(api): fix mobile navigation bug',
    'build(auth): set up CI/CD pipeline',
    'style(api): configure Sentry for error tracking',
    'docs(utils): fix loading spinner visibility',
    'chore(backend): add feature toggle system',
    'chore(cache): update Swagger docs',
    'docs(auth): improve loading speed of dashboard',
    'fix(notifications): implement debounce for search',
    'build(db): add skeleton loader for UI',
    'perf(middleware): fix typo in error message',
    'chore(notifications): remove hardcoded values',
    'refactor(db): implement debounce for search',
    'test(backend): fix CORS policy error',
    'fix(readme): refactor state management',
    'feat(backend): add integration tests for login',
    'build(deps): improve security headers',
    'docs(notifications): add feature toggle system',
    'build(utils): fix loading spinner visibility',
    'docs(readme): implement push notifications',
    'refactor(cache): add integration tests for login',
    'chore(routing): add responsive design support',
    'feat(routing): add contributing guidelines',
    'perf(auth): fix CORS policy error',
    'perf(backend): update package-lock.json',
    'refactor(api): fix mobile navigation bug',
    'feat(deps): fix mobile navigation bug',
    'feat(api): fix CORS policy error',
    'chore(ui): implement debounce for search',
    'ci(api): update deployment workflow',
    'chore(routing): optimize SQL queries',
    'ci(utils): remove unused CSS classes',
    'feat(readme): remove obsolete API endpoints',
    'build(frontend): optimize image caching',
    'docs(deps): enable gzip compression',
    'feat(readme): configure Sentry for error tracking',
    'feat(auth): optimize image caching',
    'chore(auth): implement lazy loading for images',
    'docs(ui): improve error logging',
    'style(api): implement debounce for search',
    'fix(db): configure Sentry for error tracking',
    'fix(backend): add Dockerfile for deployment',
    'chore(middleware): refactor state management',
    'build(utils): update ESLint configuration',
    'feat(ui): update Swagger docs',
    'style(notifications): add feature toggle system',
    'build(middleware): enhance user role validation',
    'fix(deps): improve error logging'
]
